In [2]:
import numpy as np

In [5]:
# Example of creating a simple array in NumPy
array = np.array([1, 2, 3, 4, 5])
array

array([1, 2, 3, 4, 5])

In [7]:
# Demonstrating reshaping an array
reshaped_array = np.reshape(array, (5, 1))
reshaped_array

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [8]:
# Performing basic mathematical operations
multiplied_array = array * 2
multiplied_array

array([ 2,  4,  6,  8, 10])

In [9]:
# Generating a random array
random_array = np.random.random((2, 2))